services:
  nethttp:
    build:
      context: .
      dockerfile: docker/Dockerfile.nethttp
    ports:
      - "8080:8080"
    networks:
      - benchmark_network

  gin:
    build:
      context: .
      dockerfile: docker/Dockerfile.gin
    ports:
      - "8081:8081"
    networks:
      - benchmark_network

  hertz:
    build:
      context: .
      dockerfile: docker/Dockerfile.hertz
    ports:
      - "8082:8082"
    networks:
      - benchmark_network

  gozero:
    build:
      context: .
      dockerfile: docker/Dockerfile.gozero
    ports:
      - "8083:8083"
    networks:
      - benchmark_network

  kratos:
    build:
      context: .
      dockerfile: docker/Dockerfile.kratos
    ports:
      - "8084:8084"
    networks:
      - benchmark_network

  benchmark:
    build:
      context: .
      dockerfile: docker/Dockerfile.benchmark
    depends_on:
      - nethttp
      - gin
      - hertz
      - gozero
      - kratos
    networks:
      - benchmark_network

networks:
  benchmark_network:
    driver: bridge

volumes:
  benchmark_results: 